si_tracker/urls.py
from django.conf.urls import url
from si_tracker import views

urlpatterns = [
    url(r'^new/(?P<type>[\w\-]+)/$', views.item_create_update, name='new_item'),
    url(r'^update/(?P<type>[\w\-]+)/(?P<item>\d+)', views.item_create_update, name='update_item'),
    url(r'^item/(?P<type>[\w\-]+)/(?P<item>\d+)', views.item, name='item'),
    url(r'^items/', views.items, name='items'),
    url(r'^$', views.general, name='general'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
    url(r'^delete/(?P<type>[\w\-]+)/(?P<item>\d+)', views.delete_item, name='delete_item'),
    url(r'^users/', views.users, name='users'),
    url(r'^create_user/', views.create_user, name='create_user'),
    url(r'^update_user/(?P<user>\d+)', views.update_user, name='update_user'),
    url(r'^change_password/(?P<user>\d+)', views.change_password, name='change_password'),

]

simpletracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('si_tracker.urls', namespace='tracker')),
]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Simple Issue Tracker</title>
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'tracker:general' %}">Simple Issue Tracker</a>
                {% if user.is_authenticated %}
                    <span class="dropdown">
                        <a class="btn btn-primary navbar-btn dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Item <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url "tracker:new_item" 'issue' %}">New Issue</a></li>
                            <li><a href="{% url "tracker:new_item" 'task' %}">New Task</a></li>
                        </ul>
                    </span>
                {% endif %}
                {% if user.is_staff %}<a class="btn btn-success navbar-btn" href="{% url 'tracker:users' %}">Users</a>{% endif %}
            </div>
            <div class="collapse navbar-collapse">
                {% if user.is_authenticated %}
                    <p class="navbar-text navbar-right">Hello, <a href="{% url 'tracker:change_password' user.id %}">{{ user }}</a> <a class="btn-link" href="{% url 'tracker:logout' %}">Logout</a></p>
                {% endif %}


            </div>
        </div>
    </nav>




    <div class="container">


        {% block content %}{% endblock %}
    </div>


</body>
</html>